project:
  type: website

website:
  title: "The Willingness to Pay for a Cooler Day"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: source.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



